name: Docker Publish x64

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: partkeepr
  VERSION_NUMBER: 1.4.0
  DOCKER_FILE: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file $DOCKER_FILE --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker tag $IMAGE_NAME f0rc3/partkeepr:latest
          docker tag $IMAGE_NAME f0rc3/partkeepr:$VERSION_NUMBER
          docker push f0rc3/partkeepr:latest
          docker push f0rc3/partkeepr:$VERSION_NUMBER
