name: Docker Publish multiarch

on:
  push:
    branches: master


env:
  VERSION_NUMBER: 1.4.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --tag buildresult --platform linux/amd64,linux/arm/v7,linux/arm64 .
          IMAGE_ID=$(docker images | awk '{print $3}' | awk 'NR==2') 
          docker tag $IMAGE_ID f0rc3/partkeepr:multiarch-latest
          docker tag $IMAGE_ID f0rc3/partkeepr:multiarch-$VERSION_NUMBER
          docker push f0rc3/partkeepr:multiarch-latest
          docker push f0rc3/partkeepr:multiarch-$VERSION_NUMBER
